[tool.poetry]
name = "engageai"
version = "1.8.3"
description = "engage ai project poetry"
authors = ["Paggie <paggie70424@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pandas = "^2.3.1"
matplotlib = "^3.10.3"
awswrangler = "^3.12.1"
boto3 = "^1.39.3"
ipykernel = "^6.29.5"
<<<<<<< HEAD
selenium = "^4.34.2"
=======
numpy = "1.26.4"
scipy = "1.13.0"
seaborn = "^0.13.2"
>>>>>>> github/master


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[[tool.poetry.packages]]
include = "research_analysis"



[tool.poetry.scripts]
access-frequency = "research_analysis.access_frequency.main:main"
session-trend = "research_analysis.session_duration.main:main"


